version: "3.9"

services:
  web:
    build: .
    working_dir: /app/dashboard
    command: python -m src.app.main
    ports:
      - "8050:8050"
    env_file:
      - .env
    restart: unless-stopped
    # Requiere curl en la imagen (ya lo tienes en tu Dockerfile)
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8050/ || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 5
    volumes:
      # Código del dashboard para hot-reload
      - type: bind
        source: ./dashboard
        target: /app/dashboard
      # (Opcional) Si algún día activas cuenta de servicio para el bot o el dashboard:
      - type: bind
        source: ./telegram_bot/service_account.json
        target: /secrets/service_account.json
        read_only: true

  bot:
    build: .
    working_dir: /app/telegram_bot
    command: python main.py
    env_file:
      - .env.bot
    restart: unless-stopped
    volumes:
      # Código del bot (edición en caliente)
      - type: bind
        source: ./telegram_bot
        target: /app/telegram_bot
      # → Secrets generados FUERA de Docker (solución 1)
      - type: bind
        source: ./secrets/credentials.json
        target: /app/telegram_bot/credentials.json
        read_only: true
      - type: bind
        source: ./secrets/token.pickle
        target: /app/telegram_bot/token.pickle
        read_only: false
